package:
  name: tailseeker
  version: 3.2.1

source:
  git_rev: v3.2.1
  git_url: https://github.com/hyeshik/tailseeker

build:
  number: 0
#  has_prefix_files:
#    - bin/tseek
#    - share/tailseeker/bin/bgzip-wrap
#    - share/tailseeker/conf/paths.conf
#  binary_has_prefix_files:
#    - 123
 
requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - zlib==1.2.13
    - htslib==1.18
  run:
    - curl==8.2.1
    - bzip2==1.0.8
    - wget==1.20.3
    - xz==5.2.6
    - zlib==1.2.13
    - lapack==3.6.0
    - openblas==0.3.23
    - ayb2==2.11.h1
    - bedtools==2.31.0
    - colormath==3.0.0
    - feather-format==0.4.1
    - gmap==2023.07.20
    - htslib==1.18
    - libblas==3.9.0
    - liblapack==3.9.0
    - matplotlib==3.7.2
    - newt==0.52.23
    - numpy==1.25.2
    - numpy-base==1.25.2
    - pandas==2.0.3
    - parallel==20170422
    - python==3.11.4
    - pyyaml==6.0
    - samtools==1.6
    - scipy==1.11.1
    - seqtk==1.4
    - snakemake==7.32.3
    - star==2.7.10b
    - xlsxwriter==3.1.2

test:
  commands:
    - tseek --version

about:
  summary: 
  home: https://github.com/hyeshik/tailseeker
